# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0a872424c90e773bf0625a9ac958269ae8dffad08afdcc531b9484318d9c76949b47417e2b77f46a348dc4d4f2cf8cccd5b1a9457b2a044f8c8363177a5c9c3

test:
  secret_key_base: 46fb8714616c6d1823a7db77bc7efe2c9605a0006cbd6013627018d7befd8ae399d8bc6fc0afdd4854d08231f4447af4301b72a4d5f037084d79c74bb79c3c28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
